### ISSUE TITLE
regular Console.log included in vdf.js

### ISSUE THREAD

**Issue by JoBoDo** [JankGaming/vdfjs#6]
line 47 of vdf.js in the root folder is logging to console for a great majority of cases.
I'm guessing that you had this in for debugging and forgot to take it out before publishing :)

Obviously I can simply comment it but thought you would like to know ^^

**Comment by twisterghost** [comment]
Awhoops. Thought I removed that. This is what I get for publishing late at night. Will fix asap.

**Comment by twisterghost** [comment]
Fixed here: c2c919b5a5eb66bb126378f82dc95559774ea1fa

Version `2.0.2` pushed to npm
