### ISSUE TITLE
Data missing from parse when a trailing comment has no content

### ISSUE THREAD

**Issue by JoBoDo** [JankGaming/vdfjs#8]
A line is not included in the json data when a lines comment does not have content

ie. Ability1 will be included but Ability2 will not

```
"Ability1"                  "customability_arcanebarrage"           // Ability 1
"Ability2"                  "customability_essenceredirect"         //
```

**Comment by JoBoDo** [comment]
sorry to have to raise all these issues haha~~~ Thanks a lot :+1:

**Comment by twisterghost** [comment]
> sorry to have to raise all these issues

No problem, thats what issues are for!
